# mingw32.cmake - MinGW 32-bit toolchain

set(CMAKE_SYSTEM_NAME Windows)

# 改成你自己的 MinGW 32-bit 路径
set(MINGW32_PATH "D:/3rdparty/mingw32")

set(CMAKE_C_COMPILER   "${MINGW32_PATH}/bin/i686-w64-mingw32-gcc.exe")
set(CMAKE_CXX_COMPILER "${MINGW32_PATH}/bin/i686-w64-mingw32-g++.exe")
set(CMAKE_RC_COMPILER  "${MINGW32_PATH}/bin/windres.exe")

set(CMAKE_FIND_ROOT_PATH ${MINGW32_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)