// proxy.h - Auto-generated for winmm.dll
// Total exports: 192
// Generated by gen_proxy.py - DO NOT EDIT

#pragma once
#include <windows.h>

extern "C" FARPROC g_proxy_fp[192];

void Proxy_Init();
void Proxy_Free();

