// proxy.cpp - Auto-generated for winmm.dll
// Total exports: 192
// Generated by gen_proxy.py - DO NOT EDIT

#include "proxy.h"
#include <cstring>

extern "C" {
    FARPROC g_proxy_fp[192] = {0};
}

static HMODULE g_hOrigDll = NULL;

// ---- Forwarding stubs (naked + basic asm) ----

extern "C" __attribute__((naked)) void proxy_CloseDriver()
{
    __asm__("jmp *(_g_proxy_fp + 0)");
}

extern "C" __attribute__((naked)) void proxy_DefDriverProc()
{
    __asm__("jmp *(_g_proxy_fp + 4)");
}

extern "C" __attribute__((naked)) void proxy_DriverCallback()
{
    __asm__("jmp *(_g_proxy_fp + 8)");
}

extern "C" __attribute__((naked)) void proxy_DrvGetModuleHandle()
{
    __asm__("jmp *(_g_proxy_fp + 12)");
}

extern "C" __attribute__((naked)) void proxy_GetDriverModuleHandle()
{
    __asm__("jmp *(_g_proxy_fp + 16)");
}

extern "C" __attribute__((naked)) void proxy_NotifyCallbackData()
{
    __asm__("jmp *(_g_proxy_fp + 20)");
}

extern "C" __attribute__((naked)) void proxy_OpenDriver()
{
    __asm__("jmp *(_g_proxy_fp + 24)");
}

extern "C" __attribute__((naked)) void proxy_PlaySound()
{
    __asm__("jmp *(_g_proxy_fp + 28)");
}

extern "C" __attribute__((naked)) void proxy_PlaySoundA()
{
    __asm__("jmp *(_g_proxy_fp + 32)");
}

extern "C" __attribute__((naked)) void proxy_PlaySoundW()
{
    __asm__("jmp *(_g_proxy_fp + 36)");
}

extern "C" __attribute__((naked)) void proxy_SendDriverMessage()
{
    __asm__("jmp *(_g_proxy_fp + 40)");
}

extern "C" __attribute__((naked)) void proxy_WOW32DriverCallback()
{
    __asm__("jmp *(_g_proxy_fp + 44)");
}

extern "C" __attribute__((naked)) void proxy_WOW32ResolveMultiMediaHandle()
{
    __asm__("jmp *(_g_proxy_fp + 48)");
}

extern "C" __attribute__((naked)) void proxy_WOWAppExit()
{
    __asm__("jmp *(_g_proxy_fp + 52)");
}

extern "C" __attribute__((naked)) void proxy_aux32Message()
{
    __asm__("jmp *(_g_proxy_fp + 56)");
}

extern "C" __attribute__((naked)) void proxy_auxGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 60)");
}

extern "C" __attribute__((naked)) void proxy_auxGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 64)");
}

extern "C" __attribute__((naked)) void proxy_auxGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 68)");
}

extern "C" __attribute__((naked)) void proxy_auxGetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 72)");
}

extern "C" __attribute__((naked)) void proxy_auxOutMessage()
{
    __asm__("jmp *(_g_proxy_fp + 76)");
}

extern "C" __attribute__((naked)) void proxy_auxSetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 80)");
}

extern "C" __attribute__((naked)) void proxy_joy32Message()
{
    __asm__("jmp *(_g_proxy_fp + 84)");
}

extern "C" __attribute__((naked)) void proxy_joyConfigChanged()
{
    __asm__("jmp *(_g_proxy_fp + 88)");
}

extern "C" __attribute__((naked)) void proxy_joyGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 92)");
}

extern "C" __attribute__((naked)) void proxy_joyGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 96)");
}

extern "C" __attribute__((naked)) void proxy_joyGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 100)");
}

extern "C" __attribute__((naked)) void proxy_joyGetPos()
{
    __asm__("jmp *(_g_proxy_fp + 104)");
}

extern "C" __attribute__((naked)) void proxy_joyGetPosEx()
{
    __asm__("jmp *(_g_proxy_fp + 108)");
}

extern "C" __attribute__((naked)) void proxy_joyGetThreshold()
{
    __asm__("jmp *(_g_proxy_fp + 112)");
}

extern "C" __attribute__((naked)) void proxy_joyReleaseCapture()
{
    __asm__("jmp *(_g_proxy_fp + 116)");
}

extern "C" __attribute__((naked)) void proxy_joySetCapture()
{
    __asm__("jmp *(_g_proxy_fp + 120)");
}

extern "C" __attribute__((naked)) void proxy_joySetThreshold()
{
    __asm__("jmp *(_g_proxy_fp + 124)");
}

extern "C" __attribute__((naked)) void proxy_mci32Message()
{
    __asm__("jmp *(_g_proxy_fp + 128)");
}

extern "C" __attribute__((naked)) void proxy_mciDriverNotify()
{
    __asm__("jmp *(_g_proxy_fp + 132)");
}

extern "C" __attribute__((naked)) void proxy_mciDriverYield()
{
    __asm__("jmp *(_g_proxy_fp + 136)");
}

extern "C" __attribute__((naked)) void proxy_mciExecute()
{
    __asm__("jmp *(_g_proxy_fp + 140)");
}

extern "C" __attribute__((naked)) void proxy_mciFreeCommandResource()
{
    __asm__("jmp *(_g_proxy_fp + 144)");
}

extern "C" __attribute__((naked)) void proxy_mciGetCreatorTask()
{
    __asm__("jmp *(_g_proxy_fp + 148)");
}

extern "C" __attribute__((naked)) void proxy_mciGetDeviceIDA()
{
    __asm__("jmp *(_g_proxy_fp + 152)");
}

extern "C" __attribute__((naked)) void proxy_mciGetDeviceIDFromElementIDA()
{
    __asm__("jmp *(_g_proxy_fp + 156)");
}

extern "C" __attribute__((naked)) void proxy_mciGetDeviceIDFromElementIDW()
{
    __asm__("jmp *(_g_proxy_fp + 160)");
}

extern "C" __attribute__((naked)) void proxy_mciGetDeviceIDW()
{
    __asm__("jmp *(_g_proxy_fp + 164)");
}

extern "C" __attribute__((naked)) void proxy_mciGetDriverData()
{
    __asm__("jmp *(_g_proxy_fp + 168)");
}

extern "C" __attribute__((naked)) void proxy_mciGetErrorStringA()
{
    __asm__("jmp *(_g_proxy_fp + 172)");
}

extern "C" __attribute__((naked)) void proxy_mciGetErrorStringW()
{
    __asm__("jmp *(_g_proxy_fp + 176)");
}

extern "C" __attribute__((naked)) void proxy_mciGetYieldProc()
{
    __asm__("jmp *(_g_proxy_fp + 180)");
}

extern "C" __attribute__((naked)) void proxy_mciLoadCommandResource()
{
    __asm__("jmp *(_g_proxy_fp + 184)");
}

extern "C" __attribute__((naked)) void proxy_mciSendCommandA()
{
    __asm__("jmp *(_g_proxy_fp + 188)");
}

extern "C" __attribute__((naked)) void proxy_mciSendCommandW()
{
    __asm__("jmp *(_g_proxy_fp + 192)");
}

extern "C" __attribute__((naked)) void proxy_mciSendStringA()
{
    __asm__("jmp *(_g_proxy_fp + 196)");
}

extern "C" __attribute__((naked)) void proxy_mciSendStringW()
{
    __asm__("jmp *(_g_proxy_fp + 200)");
}

extern "C" __attribute__((naked)) void proxy_mciSetDriverData()
{
    __asm__("jmp *(_g_proxy_fp + 204)");
}

extern "C" __attribute__((naked)) void proxy_mciSetYieldProc()
{
    __asm__("jmp *(_g_proxy_fp + 208)");
}

extern "C" __attribute__((naked)) void proxy_mid32Message()
{
    __asm__("jmp *(_g_proxy_fp + 212)");
}

extern "C" __attribute__((naked)) void proxy_midiConnect()
{
    __asm__("jmp *(_g_proxy_fp + 216)");
}

extern "C" __attribute__((naked)) void proxy_midiDisconnect()
{
    __asm__("jmp *(_g_proxy_fp + 220)");
}

extern "C" __attribute__((naked)) void proxy_midiInAddBuffer()
{
    __asm__("jmp *(_g_proxy_fp + 224)");
}

extern "C" __attribute__((naked)) void proxy_midiInClose()
{
    __asm__("jmp *(_g_proxy_fp + 228)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 232)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 236)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetErrorTextA()
{
    __asm__("jmp *(_g_proxy_fp + 240)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetErrorTextW()
{
    __asm__("jmp *(_g_proxy_fp + 244)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetID()
{
    __asm__("jmp *(_g_proxy_fp + 248)");
}

extern "C" __attribute__((naked)) void proxy_midiInGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 252)");
}

extern "C" __attribute__((naked)) void proxy_midiInMessage()
{
    __asm__("jmp *(_g_proxy_fp + 256)");
}

extern "C" __attribute__((naked)) void proxy_midiInOpen()
{
    __asm__("jmp *(_g_proxy_fp + 260)");
}

extern "C" __attribute__((naked)) void proxy_midiInPrepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 264)");
}

extern "C" __attribute__((naked)) void proxy_midiInReset()
{
    __asm__("jmp *(_g_proxy_fp + 268)");
}

extern "C" __attribute__((naked)) void proxy_midiInStart()
{
    __asm__("jmp *(_g_proxy_fp + 272)");
}

extern "C" __attribute__((naked)) void proxy_midiInStop()
{
    __asm__("jmp *(_g_proxy_fp + 276)");
}

extern "C" __attribute__((naked)) void proxy_midiInUnprepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 280)");
}

extern "C" __attribute__((naked)) void proxy_midiOutCacheDrumPatches()
{
    __asm__("jmp *(_g_proxy_fp + 284)");
}

extern "C" __attribute__((naked)) void proxy_midiOutCachePatches()
{
    __asm__("jmp *(_g_proxy_fp + 288)");
}

extern "C" __attribute__((naked)) void proxy_midiOutClose()
{
    __asm__("jmp *(_g_proxy_fp + 292)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 296)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 300)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetErrorTextA()
{
    __asm__("jmp *(_g_proxy_fp + 304)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetErrorTextW()
{
    __asm__("jmp *(_g_proxy_fp + 308)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetID()
{
    __asm__("jmp *(_g_proxy_fp + 312)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 316)");
}

extern "C" __attribute__((naked)) void proxy_midiOutGetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 320)");
}

extern "C" __attribute__((naked)) void proxy_midiOutLongMsg()
{
    __asm__("jmp *(_g_proxy_fp + 324)");
}

extern "C" __attribute__((naked)) void proxy_midiOutMessage()
{
    __asm__("jmp *(_g_proxy_fp + 328)");
}

extern "C" __attribute__((naked)) void proxy_midiOutOpen()
{
    __asm__("jmp *(_g_proxy_fp + 332)");
}

extern "C" __attribute__((naked)) void proxy_midiOutPrepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 336)");
}

extern "C" __attribute__((naked)) void proxy_midiOutReset()
{
    __asm__("jmp *(_g_proxy_fp + 340)");
}

extern "C" __attribute__((naked)) void proxy_midiOutSetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 344)");
}

extern "C" __attribute__((naked)) void proxy_midiOutShortMsg()
{
    __asm__("jmp *(_g_proxy_fp + 348)");
}

extern "C" __attribute__((naked)) void proxy_midiOutUnprepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 352)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamClose()
{
    __asm__("jmp *(_g_proxy_fp + 356)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamOpen()
{
    __asm__("jmp *(_g_proxy_fp + 360)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamOut()
{
    __asm__("jmp *(_g_proxy_fp + 364)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamPause()
{
    __asm__("jmp *(_g_proxy_fp + 368)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamPosition()
{
    __asm__("jmp *(_g_proxy_fp + 372)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamProperty()
{
    __asm__("jmp *(_g_proxy_fp + 376)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamRestart()
{
    __asm__("jmp *(_g_proxy_fp + 380)");
}

extern "C" __attribute__((naked)) void proxy_midiStreamStop()
{
    __asm__("jmp *(_g_proxy_fp + 384)");
}

extern "C" __attribute__((naked)) void proxy_mixerClose()
{
    __asm__("jmp *(_g_proxy_fp + 388)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetControlDetailsA()
{
    __asm__("jmp *(_g_proxy_fp + 392)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetControlDetailsW()
{
    __asm__("jmp *(_g_proxy_fp + 396)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 400)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 404)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetID()
{
    __asm__("jmp *(_g_proxy_fp + 408)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetLineControlsA()
{
    __asm__("jmp *(_g_proxy_fp + 412)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetLineControlsW()
{
    __asm__("jmp *(_g_proxy_fp + 416)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetLineInfoA()
{
    __asm__("jmp *(_g_proxy_fp + 420)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetLineInfoW()
{
    __asm__("jmp *(_g_proxy_fp + 424)");
}

extern "C" __attribute__((naked)) void proxy_mixerGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 428)");
}

extern "C" __attribute__((naked)) void proxy_mixerMessage()
{
    __asm__("jmp *(_g_proxy_fp + 432)");
}

extern "C" __attribute__((naked)) void proxy_mixerOpen()
{
    __asm__("jmp *(_g_proxy_fp + 436)");
}

extern "C" __attribute__((naked)) void proxy_mixerSetControlDetails()
{
    __asm__("jmp *(_g_proxy_fp + 440)");
}

extern "C" __attribute__((naked)) void proxy_mmDrvInstall()
{
    __asm__("jmp *(_g_proxy_fp + 444)");
}

extern "C" __attribute__((naked)) void proxy_mmGetCurrentTask()
{
    __asm__("jmp *(_g_proxy_fp + 448)");
}

extern "C" __attribute__((naked)) void proxy_mmTaskBlock()
{
    __asm__("jmp *(_g_proxy_fp + 452)");
}

extern "C" __attribute__((naked)) void proxy_mmTaskCreate()
{
    __asm__("jmp *(_g_proxy_fp + 456)");
}

extern "C" __attribute__((naked)) void proxy_mmTaskSignal()
{
    __asm__("jmp *(_g_proxy_fp + 460)");
}

extern "C" __attribute__((naked)) void proxy_mmTaskYield()
{
    __asm__("jmp *(_g_proxy_fp + 464)");
}

extern "C" __attribute__((naked)) void proxy_mmioAdvance()
{
    __asm__("jmp *(_g_proxy_fp + 468)");
}

extern "C" __attribute__((naked)) void proxy_mmioAscend()
{
    __asm__("jmp *(_g_proxy_fp + 472)");
}

extern "C" __attribute__((naked)) void proxy_mmioClose()
{
    __asm__("jmp *(_g_proxy_fp + 476)");
}

extern "C" __attribute__((naked)) void proxy_mmioCreateChunk()
{
    __asm__("jmp *(_g_proxy_fp + 480)");
}

extern "C" __attribute__((naked)) void proxy_mmioDescend()
{
    __asm__("jmp *(_g_proxy_fp + 484)");
}

extern "C" __attribute__((naked)) void proxy_mmioFlush()
{
    __asm__("jmp *(_g_proxy_fp + 488)");
}

extern "C" __attribute__((naked)) void proxy_mmioGetInfo()
{
    __asm__("jmp *(_g_proxy_fp + 492)");
}

extern "C" __attribute__((naked)) void proxy_mmioInstallIOProcA()
{
    __asm__("jmp *(_g_proxy_fp + 496)");
}

extern "C" __attribute__((naked)) void proxy_mmioInstallIOProcW()
{
    __asm__("jmp *(_g_proxy_fp + 500)");
}

extern "C" __attribute__((naked)) void proxy_mmioOpenA()
{
    __asm__("jmp *(_g_proxy_fp + 504)");
}

extern "C" __attribute__((naked)) void proxy_mmioOpenW()
{
    __asm__("jmp *(_g_proxy_fp + 508)");
}

extern "C" __attribute__((naked)) void proxy_mmioRead()
{
    __asm__("jmp *(_g_proxy_fp + 512)");
}

extern "C" __attribute__((naked)) void proxy_mmioRenameA()
{
    __asm__("jmp *(_g_proxy_fp + 516)");
}

extern "C" __attribute__((naked)) void proxy_mmioRenameW()
{
    __asm__("jmp *(_g_proxy_fp + 520)");
}

extern "C" __attribute__((naked)) void proxy_mmioSeek()
{
    __asm__("jmp *(_g_proxy_fp + 524)");
}

extern "C" __attribute__((naked)) void proxy_mmioSendMessage()
{
    __asm__("jmp *(_g_proxy_fp + 528)");
}

extern "C" __attribute__((naked)) void proxy_mmioSetBuffer()
{
    __asm__("jmp *(_g_proxy_fp + 532)");
}

extern "C" __attribute__((naked)) void proxy_mmioSetInfo()
{
    __asm__("jmp *(_g_proxy_fp + 536)");
}

extern "C" __attribute__((naked)) void proxy_mmioStringToFOURCCA()
{
    __asm__("jmp *(_g_proxy_fp + 540)");
}

extern "C" __attribute__((naked)) void proxy_mmioStringToFOURCCW()
{
    __asm__("jmp *(_g_proxy_fp + 544)");
}

extern "C" __attribute__((naked)) void proxy_mmioWrite()
{
    __asm__("jmp *(_g_proxy_fp + 548)");
}

extern "C" __attribute__((naked)) void proxy_mmsystemGetVersion()
{
    __asm__("jmp *(_g_proxy_fp + 552)");
}

extern "C" __attribute__((naked)) void proxy_mod32Message()
{
    __asm__("jmp *(_g_proxy_fp + 556)");
}

extern "C" __attribute__((naked)) void proxy_mxd32Message()
{
    __asm__("jmp *(_g_proxy_fp + 560)");
}

extern "C" __attribute__((naked)) void proxy_sndPlaySoundA()
{
    __asm__("jmp *(_g_proxy_fp + 564)");
}

extern "C" __attribute__((naked)) void proxy_sndPlaySoundW()
{
    __asm__("jmp *(_g_proxy_fp + 568)");
}

extern "C" __attribute__((naked)) void proxy_tid32Message()
{
    __asm__("jmp *(_g_proxy_fp + 572)");
}

extern "C" __attribute__((naked)) void proxy_timeBeginPeriod()
{
    __asm__("jmp *(_g_proxy_fp + 576)");
}

extern "C" __attribute__((naked)) void proxy_timeEndPeriod()
{
    __asm__("jmp *(_g_proxy_fp + 580)");
}

extern "C" __attribute__((naked)) void proxy_timeGetDevCaps()
{
    __asm__("jmp *(_g_proxy_fp + 584)");
}

extern "C" __attribute__((naked)) void proxy_timeGetSystemTime()
{
    __asm__("jmp *(_g_proxy_fp + 588)");
}

extern "C" __attribute__((naked)) void proxy_timeGetTime()
{
    __asm__("jmp *(_g_proxy_fp + 592)");
}

extern "C" __attribute__((naked)) void proxy_timeKillEvent()
{
    __asm__("jmp *(_g_proxy_fp + 596)");
}

extern "C" __attribute__((naked)) void proxy_timeSetEvent()
{
    __asm__("jmp *(_g_proxy_fp + 600)");
}

extern "C" __attribute__((naked)) void proxy_waveInAddBuffer()
{
    __asm__("jmp *(_g_proxy_fp + 604)");
}

extern "C" __attribute__((naked)) void proxy_waveInClose()
{
    __asm__("jmp *(_g_proxy_fp + 608)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 612)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 616)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetErrorTextA()
{
    __asm__("jmp *(_g_proxy_fp + 620)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetErrorTextW()
{
    __asm__("jmp *(_g_proxy_fp + 624)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetID()
{
    __asm__("jmp *(_g_proxy_fp + 628)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 632)");
}

extern "C" __attribute__((naked)) void proxy_waveInGetPosition()
{
    __asm__("jmp *(_g_proxy_fp + 636)");
}

extern "C" __attribute__((naked)) void proxy_waveInMessage()
{
    __asm__("jmp *(_g_proxy_fp + 640)");
}

extern "C" __attribute__((naked)) void proxy_waveInOpen()
{
    __asm__("jmp *(_g_proxy_fp + 644)");
}

extern "C" __attribute__((naked)) void proxy_waveInPrepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 648)");
}

extern "C" __attribute__((naked)) void proxy_waveInReset()
{
    __asm__("jmp *(_g_proxy_fp + 652)");
}

extern "C" __attribute__((naked)) void proxy_waveInStart()
{
    __asm__("jmp *(_g_proxy_fp + 656)");
}

extern "C" __attribute__((naked)) void proxy_waveInStop()
{
    __asm__("jmp *(_g_proxy_fp + 660)");
}

extern "C" __attribute__((naked)) void proxy_waveInUnprepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 664)");
}

extern "C" __attribute__((naked)) void proxy_waveOutBreakLoop()
{
    __asm__("jmp *(_g_proxy_fp + 668)");
}

extern "C" __attribute__((naked)) void proxy_waveOutClose()
{
    __asm__("jmp *(_g_proxy_fp + 672)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetDevCapsA()
{
    __asm__("jmp *(_g_proxy_fp + 676)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetDevCapsW()
{
    __asm__("jmp *(_g_proxy_fp + 680)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetErrorTextA()
{
    __asm__("jmp *(_g_proxy_fp + 684)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetErrorTextW()
{
    __asm__("jmp *(_g_proxy_fp + 688)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetID()
{
    __asm__("jmp *(_g_proxy_fp + 692)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetNumDevs()
{
    __asm__("jmp *(_g_proxy_fp + 696)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetPitch()
{
    __asm__("jmp *(_g_proxy_fp + 700)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetPlaybackRate()
{
    __asm__("jmp *(_g_proxy_fp + 704)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetPosition()
{
    __asm__("jmp *(_g_proxy_fp + 708)");
}

extern "C" __attribute__((naked)) void proxy_waveOutGetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 712)");
}

extern "C" __attribute__((naked)) void proxy_waveOutMessage()
{
    __asm__("jmp *(_g_proxy_fp + 716)");
}

extern "C" __attribute__((naked)) void proxy_waveOutOpen()
{
    __asm__("jmp *(_g_proxy_fp + 720)");
}

extern "C" __attribute__((naked)) void proxy_waveOutPause()
{
    __asm__("jmp *(_g_proxy_fp + 724)");
}

extern "C" __attribute__((naked)) void proxy_waveOutPrepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 728)");
}

extern "C" __attribute__((naked)) void proxy_waveOutReset()
{
    __asm__("jmp *(_g_proxy_fp + 732)");
}

extern "C" __attribute__((naked)) void proxy_waveOutRestart()
{
    __asm__("jmp *(_g_proxy_fp + 736)");
}

extern "C" __attribute__((naked)) void proxy_waveOutSetPitch()
{
    __asm__("jmp *(_g_proxy_fp + 740)");
}

extern "C" __attribute__((naked)) void proxy_waveOutSetPlaybackRate()
{
    __asm__("jmp *(_g_proxy_fp + 744)");
}

extern "C" __attribute__((naked)) void proxy_waveOutSetVolume()
{
    __asm__("jmp *(_g_proxy_fp + 748)");
}

extern "C" __attribute__((naked)) void proxy_waveOutUnprepareHeader()
{
    __asm__("jmp *(_g_proxy_fp + 752)");
}

extern "C" __attribute__((naked)) void proxy_waveOutWrite()
{
    __asm__("jmp *(_g_proxy_fp + 756)");
}

extern "C" __attribute__((naked)) void proxy_wid32Message()
{
    __asm__("jmp *(_g_proxy_fp + 760)");
}

extern "C" __attribute__((naked)) void proxy_wod32Message()
{
    __asm__("jmp *(_g_proxy_fp + 764)");
}

void Proxy_Init()
{
    char path[MAX_PATH];
    GetSystemDirectoryA(path, MAX_PATH);
    strcat(path, "\\winmm.dll");
    g_hOrigDll = LoadLibraryA(path);
    if (!g_hOrigDll) return;

    g_proxy_fp[  0] = GetProcAddress(g_hOrigDll, "CloseDriver");
    g_proxy_fp[  1] = GetProcAddress(g_hOrigDll, "DefDriverProc");
    g_proxy_fp[  2] = GetProcAddress(g_hOrigDll, "DriverCallback");
    g_proxy_fp[  3] = GetProcAddress(g_hOrigDll, "DrvGetModuleHandle");
    g_proxy_fp[  4] = GetProcAddress(g_hOrigDll, "GetDriverModuleHandle");
    g_proxy_fp[  5] = GetProcAddress(g_hOrigDll, "NotifyCallbackData");
    g_proxy_fp[  6] = GetProcAddress(g_hOrigDll, "OpenDriver");
    g_proxy_fp[  7] = GetProcAddress(g_hOrigDll, "PlaySound");
    g_proxy_fp[  8] = GetProcAddress(g_hOrigDll, "PlaySoundA");
    g_proxy_fp[  9] = GetProcAddress(g_hOrigDll, "PlaySoundW");
    g_proxy_fp[ 10] = GetProcAddress(g_hOrigDll, "SendDriverMessage");
    g_proxy_fp[ 11] = GetProcAddress(g_hOrigDll, "WOW32DriverCallback");
    g_proxy_fp[ 12] = GetProcAddress(g_hOrigDll, "WOW32ResolveMultiMediaHandle");
    g_proxy_fp[ 13] = GetProcAddress(g_hOrigDll, "WOWAppExit");
    g_proxy_fp[ 14] = GetProcAddress(g_hOrigDll, "aux32Message");
    g_proxy_fp[ 15] = GetProcAddress(g_hOrigDll, "auxGetDevCapsA");
    g_proxy_fp[ 16] = GetProcAddress(g_hOrigDll, "auxGetDevCapsW");
    g_proxy_fp[ 17] = GetProcAddress(g_hOrigDll, "auxGetNumDevs");
    g_proxy_fp[ 18] = GetProcAddress(g_hOrigDll, "auxGetVolume");
    g_proxy_fp[ 19] = GetProcAddress(g_hOrigDll, "auxOutMessage");
    g_proxy_fp[ 20] = GetProcAddress(g_hOrigDll, "auxSetVolume");
    g_proxy_fp[ 21] = GetProcAddress(g_hOrigDll, "joy32Message");
    g_proxy_fp[ 22] = GetProcAddress(g_hOrigDll, "joyConfigChanged");
    g_proxy_fp[ 23] = GetProcAddress(g_hOrigDll, "joyGetDevCapsA");
    g_proxy_fp[ 24] = GetProcAddress(g_hOrigDll, "joyGetDevCapsW");
    g_proxy_fp[ 25] = GetProcAddress(g_hOrigDll, "joyGetNumDevs");
    g_proxy_fp[ 26] = GetProcAddress(g_hOrigDll, "joyGetPos");
    g_proxy_fp[ 27] = GetProcAddress(g_hOrigDll, "joyGetPosEx");
    g_proxy_fp[ 28] = GetProcAddress(g_hOrigDll, "joyGetThreshold");
    g_proxy_fp[ 29] = GetProcAddress(g_hOrigDll, "joyReleaseCapture");
    g_proxy_fp[ 30] = GetProcAddress(g_hOrigDll, "joySetCapture");
    g_proxy_fp[ 31] = GetProcAddress(g_hOrigDll, "joySetThreshold");
    g_proxy_fp[ 32] = GetProcAddress(g_hOrigDll, "mci32Message");
    g_proxy_fp[ 33] = GetProcAddress(g_hOrigDll, "mciDriverNotify");
    g_proxy_fp[ 34] = GetProcAddress(g_hOrigDll, "mciDriverYield");
    g_proxy_fp[ 35] = GetProcAddress(g_hOrigDll, "mciExecute");
    g_proxy_fp[ 36] = GetProcAddress(g_hOrigDll, "mciFreeCommandResource");
    g_proxy_fp[ 37] = GetProcAddress(g_hOrigDll, "mciGetCreatorTask");
    g_proxy_fp[ 38] = GetProcAddress(g_hOrigDll, "mciGetDeviceIDA");
    g_proxy_fp[ 39] = GetProcAddress(g_hOrigDll, "mciGetDeviceIDFromElementIDA");
    g_proxy_fp[ 40] = GetProcAddress(g_hOrigDll, "mciGetDeviceIDFromElementIDW");
    g_proxy_fp[ 41] = GetProcAddress(g_hOrigDll, "mciGetDeviceIDW");
    g_proxy_fp[ 42] = GetProcAddress(g_hOrigDll, "mciGetDriverData");
    g_proxy_fp[ 43] = GetProcAddress(g_hOrigDll, "mciGetErrorStringA");
    g_proxy_fp[ 44] = GetProcAddress(g_hOrigDll, "mciGetErrorStringW");
    g_proxy_fp[ 45] = GetProcAddress(g_hOrigDll, "mciGetYieldProc");
    g_proxy_fp[ 46] = GetProcAddress(g_hOrigDll, "mciLoadCommandResource");
    g_proxy_fp[ 47] = GetProcAddress(g_hOrigDll, "mciSendCommandA");
    g_proxy_fp[ 48] = GetProcAddress(g_hOrigDll, "mciSendCommandW");
    g_proxy_fp[ 49] = GetProcAddress(g_hOrigDll, "mciSendStringA");
    g_proxy_fp[ 50] = GetProcAddress(g_hOrigDll, "mciSendStringW");
    g_proxy_fp[ 51] = GetProcAddress(g_hOrigDll, "mciSetDriverData");
    g_proxy_fp[ 52] = GetProcAddress(g_hOrigDll, "mciSetYieldProc");
    g_proxy_fp[ 53] = GetProcAddress(g_hOrigDll, "mid32Message");
    g_proxy_fp[ 54] = GetProcAddress(g_hOrigDll, "midiConnect");
    g_proxy_fp[ 55] = GetProcAddress(g_hOrigDll, "midiDisconnect");
    g_proxy_fp[ 56] = GetProcAddress(g_hOrigDll, "midiInAddBuffer");
    g_proxy_fp[ 57] = GetProcAddress(g_hOrigDll, "midiInClose");
    g_proxy_fp[ 58] = GetProcAddress(g_hOrigDll, "midiInGetDevCapsA");
    g_proxy_fp[ 59] = GetProcAddress(g_hOrigDll, "midiInGetDevCapsW");
    g_proxy_fp[ 60] = GetProcAddress(g_hOrigDll, "midiInGetErrorTextA");
    g_proxy_fp[ 61] = GetProcAddress(g_hOrigDll, "midiInGetErrorTextW");
    g_proxy_fp[ 62] = GetProcAddress(g_hOrigDll, "midiInGetID");
    g_proxy_fp[ 63] = GetProcAddress(g_hOrigDll, "midiInGetNumDevs");
    g_proxy_fp[ 64] = GetProcAddress(g_hOrigDll, "midiInMessage");
    g_proxy_fp[ 65] = GetProcAddress(g_hOrigDll, "midiInOpen");
    g_proxy_fp[ 66] = GetProcAddress(g_hOrigDll, "midiInPrepareHeader");
    g_proxy_fp[ 67] = GetProcAddress(g_hOrigDll, "midiInReset");
    g_proxy_fp[ 68] = GetProcAddress(g_hOrigDll, "midiInStart");
    g_proxy_fp[ 69] = GetProcAddress(g_hOrigDll, "midiInStop");
    g_proxy_fp[ 70] = GetProcAddress(g_hOrigDll, "midiInUnprepareHeader");
    g_proxy_fp[ 71] = GetProcAddress(g_hOrigDll, "midiOutCacheDrumPatches");
    g_proxy_fp[ 72] = GetProcAddress(g_hOrigDll, "midiOutCachePatches");
    g_proxy_fp[ 73] = GetProcAddress(g_hOrigDll, "midiOutClose");
    g_proxy_fp[ 74] = GetProcAddress(g_hOrigDll, "midiOutGetDevCapsA");
    g_proxy_fp[ 75] = GetProcAddress(g_hOrigDll, "midiOutGetDevCapsW");
    g_proxy_fp[ 76] = GetProcAddress(g_hOrigDll, "midiOutGetErrorTextA");
    g_proxy_fp[ 77] = GetProcAddress(g_hOrigDll, "midiOutGetErrorTextW");
    g_proxy_fp[ 78] = GetProcAddress(g_hOrigDll, "midiOutGetID");
    g_proxy_fp[ 79] = GetProcAddress(g_hOrigDll, "midiOutGetNumDevs");
    g_proxy_fp[ 80] = GetProcAddress(g_hOrigDll, "midiOutGetVolume");
    g_proxy_fp[ 81] = GetProcAddress(g_hOrigDll, "midiOutLongMsg");
    g_proxy_fp[ 82] = GetProcAddress(g_hOrigDll, "midiOutMessage");
    g_proxy_fp[ 83] = GetProcAddress(g_hOrigDll, "midiOutOpen");
    g_proxy_fp[ 84] = GetProcAddress(g_hOrigDll, "midiOutPrepareHeader");
    g_proxy_fp[ 85] = GetProcAddress(g_hOrigDll, "midiOutReset");
    g_proxy_fp[ 86] = GetProcAddress(g_hOrigDll, "midiOutSetVolume");
    g_proxy_fp[ 87] = GetProcAddress(g_hOrigDll, "midiOutShortMsg");
    g_proxy_fp[ 88] = GetProcAddress(g_hOrigDll, "midiOutUnprepareHeader");
    g_proxy_fp[ 89] = GetProcAddress(g_hOrigDll, "midiStreamClose");
    g_proxy_fp[ 90] = GetProcAddress(g_hOrigDll, "midiStreamOpen");
    g_proxy_fp[ 91] = GetProcAddress(g_hOrigDll, "midiStreamOut");
    g_proxy_fp[ 92] = GetProcAddress(g_hOrigDll, "midiStreamPause");
    g_proxy_fp[ 93] = GetProcAddress(g_hOrigDll, "midiStreamPosition");
    g_proxy_fp[ 94] = GetProcAddress(g_hOrigDll, "midiStreamProperty");
    g_proxy_fp[ 95] = GetProcAddress(g_hOrigDll, "midiStreamRestart");
    g_proxy_fp[ 96] = GetProcAddress(g_hOrigDll, "midiStreamStop");
    g_proxy_fp[ 97] = GetProcAddress(g_hOrigDll, "mixerClose");
    g_proxy_fp[ 98] = GetProcAddress(g_hOrigDll, "mixerGetControlDetailsA");
    g_proxy_fp[ 99] = GetProcAddress(g_hOrigDll, "mixerGetControlDetailsW");
    g_proxy_fp[100] = GetProcAddress(g_hOrigDll, "mixerGetDevCapsA");
    g_proxy_fp[101] = GetProcAddress(g_hOrigDll, "mixerGetDevCapsW");
    g_proxy_fp[102] = GetProcAddress(g_hOrigDll, "mixerGetID");
    g_proxy_fp[103] = GetProcAddress(g_hOrigDll, "mixerGetLineControlsA");
    g_proxy_fp[104] = GetProcAddress(g_hOrigDll, "mixerGetLineControlsW");
    g_proxy_fp[105] = GetProcAddress(g_hOrigDll, "mixerGetLineInfoA");
    g_proxy_fp[106] = GetProcAddress(g_hOrigDll, "mixerGetLineInfoW");
    g_proxy_fp[107] = GetProcAddress(g_hOrigDll, "mixerGetNumDevs");
    g_proxy_fp[108] = GetProcAddress(g_hOrigDll, "mixerMessage");
    g_proxy_fp[109] = GetProcAddress(g_hOrigDll, "mixerOpen");
    g_proxy_fp[110] = GetProcAddress(g_hOrigDll, "mixerSetControlDetails");
    g_proxy_fp[111] = GetProcAddress(g_hOrigDll, "mmDrvInstall");
    g_proxy_fp[112] = GetProcAddress(g_hOrigDll, "mmGetCurrentTask");
    g_proxy_fp[113] = GetProcAddress(g_hOrigDll, "mmTaskBlock");
    g_proxy_fp[114] = GetProcAddress(g_hOrigDll, "mmTaskCreate");
    g_proxy_fp[115] = GetProcAddress(g_hOrigDll, "mmTaskSignal");
    g_proxy_fp[116] = GetProcAddress(g_hOrigDll, "mmTaskYield");
    g_proxy_fp[117] = GetProcAddress(g_hOrigDll, "mmioAdvance");
    g_proxy_fp[118] = GetProcAddress(g_hOrigDll, "mmioAscend");
    g_proxy_fp[119] = GetProcAddress(g_hOrigDll, "mmioClose");
    g_proxy_fp[120] = GetProcAddress(g_hOrigDll, "mmioCreateChunk");
    g_proxy_fp[121] = GetProcAddress(g_hOrigDll, "mmioDescend");
    g_proxy_fp[122] = GetProcAddress(g_hOrigDll, "mmioFlush");
    g_proxy_fp[123] = GetProcAddress(g_hOrigDll, "mmioGetInfo");
    g_proxy_fp[124] = GetProcAddress(g_hOrigDll, "mmioInstallIOProcA");
    g_proxy_fp[125] = GetProcAddress(g_hOrigDll, "mmioInstallIOProcW");
    g_proxy_fp[126] = GetProcAddress(g_hOrigDll, "mmioOpenA");
    g_proxy_fp[127] = GetProcAddress(g_hOrigDll, "mmioOpenW");
    g_proxy_fp[128] = GetProcAddress(g_hOrigDll, "mmioRead");
    g_proxy_fp[129] = GetProcAddress(g_hOrigDll, "mmioRenameA");
    g_proxy_fp[130] = GetProcAddress(g_hOrigDll, "mmioRenameW");
    g_proxy_fp[131] = GetProcAddress(g_hOrigDll, "mmioSeek");
    g_proxy_fp[132] = GetProcAddress(g_hOrigDll, "mmioSendMessage");
    g_proxy_fp[133] = GetProcAddress(g_hOrigDll, "mmioSetBuffer");
    g_proxy_fp[134] = GetProcAddress(g_hOrigDll, "mmioSetInfo");
    g_proxy_fp[135] = GetProcAddress(g_hOrigDll, "mmioStringToFOURCCA");
    g_proxy_fp[136] = GetProcAddress(g_hOrigDll, "mmioStringToFOURCCW");
    g_proxy_fp[137] = GetProcAddress(g_hOrigDll, "mmioWrite");
    g_proxy_fp[138] = GetProcAddress(g_hOrigDll, "mmsystemGetVersion");
    g_proxy_fp[139] = GetProcAddress(g_hOrigDll, "mod32Message");
    g_proxy_fp[140] = GetProcAddress(g_hOrigDll, "mxd32Message");
    g_proxy_fp[141] = GetProcAddress(g_hOrigDll, "sndPlaySoundA");
    g_proxy_fp[142] = GetProcAddress(g_hOrigDll, "sndPlaySoundW");
    g_proxy_fp[143] = GetProcAddress(g_hOrigDll, "tid32Message");
    g_proxy_fp[144] = GetProcAddress(g_hOrigDll, "timeBeginPeriod");
    g_proxy_fp[145] = GetProcAddress(g_hOrigDll, "timeEndPeriod");
    g_proxy_fp[146] = GetProcAddress(g_hOrigDll, "timeGetDevCaps");
    g_proxy_fp[147] = GetProcAddress(g_hOrigDll, "timeGetSystemTime");
    g_proxy_fp[148] = GetProcAddress(g_hOrigDll, "timeGetTime");
    g_proxy_fp[149] = GetProcAddress(g_hOrigDll, "timeKillEvent");
    g_proxy_fp[150] = GetProcAddress(g_hOrigDll, "timeSetEvent");
    g_proxy_fp[151] = GetProcAddress(g_hOrigDll, "waveInAddBuffer");
    g_proxy_fp[152] = GetProcAddress(g_hOrigDll, "waveInClose");
    g_proxy_fp[153] = GetProcAddress(g_hOrigDll, "waveInGetDevCapsA");
    g_proxy_fp[154] = GetProcAddress(g_hOrigDll, "waveInGetDevCapsW");
    g_proxy_fp[155] = GetProcAddress(g_hOrigDll, "waveInGetErrorTextA");
    g_proxy_fp[156] = GetProcAddress(g_hOrigDll, "waveInGetErrorTextW");
    g_proxy_fp[157] = GetProcAddress(g_hOrigDll, "waveInGetID");
    g_proxy_fp[158] = GetProcAddress(g_hOrigDll, "waveInGetNumDevs");
    g_proxy_fp[159] = GetProcAddress(g_hOrigDll, "waveInGetPosition");
    g_proxy_fp[160] = GetProcAddress(g_hOrigDll, "waveInMessage");
    g_proxy_fp[161] = GetProcAddress(g_hOrigDll, "waveInOpen");
    g_proxy_fp[162] = GetProcAddress(g_hOrigDll, "waveInPrepareHeader");
    g_proxy_fp[163] = GetProcAddress(g_hOrigDll, "waveInReset");
    g_proxy_fp[164] = GetProcAddress(g_hOrigDll, "waveInStart");
    g_proxy_fp[165] = GetProcAddress(g_hOrigDll, "waveInStop");
    g_proxy_fp[166] = GetProcAddress(g_hOrigDll, "waveInUnprepareHeader");
    g_proxy_fp[167] = GetProcAddress(g_hOrigDll, "waveOutBreakLoop");
    g_proxy_fp[168] = GetProcAddress(g_hOrigDll, "waveOutClose");
    g_proxy_fp[169] = GetProcAddress(g_hOrigDll, "waveOutGetDevCapsA");
    g_proxy_fp[170] = GetProcAddress(g_hOrigDll, "waveOutGetDevCapsW");
    g_proxy_fp[171] = GetProcAddress(g_hOrigDll, "waveOutGetErrorTextA");
    g_proxy_fp[172] = GetProcAddress(g_hOrigDll, "waveOutGetErrorTextW");
    g_proxy_fp[173] = GetProcAddress(g_hOrigDll, "waveOutGetID");
    g_proxy_fp[174] = GetProcAddress(g_hOrigDll, "waveOutGetNumDevs");
    g_proxy_fp[175] = GetProcAddress(g_hOrigDll, "waveOutGetPitch");
    g_proxy_fp[176] = GetProcAddress(g_hOrigDll, "waveOutGetPlaybackRate");
    g_proxy_fp[177] = GetProcAddress(g_hOrigDll, "waveOutGetPosition");
    g_proxy_fp[178] = GetProcAddress(g_hOrigDll, "waveOutGetVolume");
    g_proxy_fp[179] = GetProcAddress(g_hOrigDll, "waveOutMessage");
    g_proxy_fp[180] = GetProcAddress(g_hOrigDll, "waveOutOpen");
    g_proxy_fp[181] = GetProcAddress(g_hOrigDll, "waveOutPause");
    g_proxy_fp[182] = GetProcAddress(g_hOrigDll, "waveOutPrepareHeader");
    g_proxy_fp[183] = GetProcAddress(g_hOrigDll, "waveOutReset");
    g_proxy_fp[184] = GetProcAddress(g_hOrigDll, "waveOutRestart");
    g_proxy_fp[185] = GetProcAddress(g_hOrigDll, "waveOutSetPitch");
    g_proxy_fp[186] = GetProcAddress(g_hOrigDll, "waveOutSetPlaybackRate");
    g_proxy_fp[187] = GetProcAddress(g_hOrigDll, "waveOutSetVolume");
    g_proxy_fp[188] = GetProcAddress(g_hOrigDll, "waveOutUnprepareHeader");
    g_proxy_fp[189] = GetProcAddress(g_hOrigDll, "waveOutWrite");
    g_proxy_fp[190] = GetProcAddress(g_hOrigDll, "wid32Message");
    g_proxy_fp[191] = GetProcAddress(g_hOrigDll, "wod32Message");
}

void Proxy_Free()
{
    if (g_hOrigDll) { FreeLibrary(g_hOrigDll); g_hOrigDll = NULL; }
}

